Enhance Dapr Bot
dapr/js-sdk pull request #210
Opened 2022-03-10 09:46 UTC by shubham1172

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description

Adds a few more features to the dapr bot
1. Cron job to mark issues and PR stale
2. `/ok-to-e2e-test` to retrigger end to end tests
3. `/ping-author` to add special label `needs-author-feedback`
4. Replacing `needs-author-feedback` with `needs-team-attention` when author replies after (3)

## Issue reference

Please reference the issue this PR will close: #208 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* (NA) Code compiles correctly
* (NA) Created/updated tests
* (NA) Extended the documentation

2022-03-10 15:03 UTC, tanvigour reviewed
I think we should also have something for better stale management of issues. For example, if there's no activity for say 3 days, ping a maintainer?

2022-03-10 16:10 UTC, shubham1172 commented
@tanvigour I can think of two scenarios here.
1. User opens an issue saying "Help with XYZ" and when we ask for more context, they ghost us. In this case, the action item is on them, and stale bot will simply mark stale/close it after threshold days.
2. There is a feature request/bug which requires action item from a contributor/maintainer. In this case, the stale bot should not close the issue. This can be prevented by adding special labels to the issue (mentioned in the workflow).

There is another aspect to it. Maintainers and contributors are responsible for regularly triaging the issues. They also have their GitHub notifications already hot, so any ping we might add will add to the noise. Plus, it is possible that the action item is already on a single maintainer, so in that case, how do we ping only the person who's responsible? IMO, we can skip this feature for now and manually keep an eye on issues. Case (1) above is the purpose of the stale bot, and Case (2) can be avoided  by regular triaging of the repository (the maintainer can simply add the label `triaged/resolved`).

Also, this repository does not see a huge flux of issues. The current count is also very less. Chances are that each issue is already under a contributor's radar.

Please feel free to share your thoughts - @XavierGeerinck @amulyavarote

2022-03-15 16:02 UTC, XavierGeerinck commented
I agree with you @shubham1172 I would however tag wise look at the `needs-author-feedback` and `needs-team-attention` labels instead of `triaged/resolved`? Seeing that those are the "`ping/pong`" mechanism and only ping us whenever we know there is an action at our side. It will also prevent the stale bot removing those issues

2022-03-21 20:57 UTC, tanvigour approved these changes

2022-03-21 21:04 UTC, amulyavarote submitted a review, later dismissed

2022-03-28 13:33 UTC, shubham1172 commented
@XavierGeerinck 

> I agree with you @shubham1172 I would however tag wise look at the `needs-author-feedback` and `needs-team-attention` labels instead of `triaged/resolved`? Seeing that those are the "`ping/pong`" mechanism and only ping us whenever we know there is an action at our side. It will also prevent the stale bot removing those issues

When an issue is tagged with `needs-author-feedback`, we should still be able to mark them stale, right? Say someone posted an issue where they are facing XYZ issues and we ask for more information, adding the tag `needs-author-feedback`, but they don't get back in 60 days.

2022-03-28 17:00 UTC, XavierGeerinck commented on .github/scripts/dapr_bot.js
> +    var response = await github.issues.listLabelsOnIssue({
I would use `const`

2022-03-28 17:11 UTC, XavierGeerinck requested changes
Overal "fine" some minor style changes.

Big question I have: Wouldn't it be easier and more readable if we process by comment body and respective functions?

E.g. (pseudo wise)

```
switch (commentBody) {
    case "/assign":
        executeAssign();
        break;
    case "/other":
        executeOther();
        break;
}
```

2022-03-28 17:11 UTC, XavierGeerinck commented on .github/scripts/dapr_bot.js
> +    var labelNames = response.data.map((i) => i.name)
`const`

2022-03-28 17:11 UTC, XavierGeerinck commented on .github/scripts/dapr_bot.js
> +    if (isFromPulls && commentBody) {
1 if statement?

2022-03-29 02:32 UTC, shubham1172 commented on .github/scripts/dapr_bot.js
> +            await fn()
This is better! Thanks!

2022-03-29 03:36 UTC, shubham1172 commented
> Overal "fine" some minor style changes.
> 
> Big question I have: Wouldn't it be easier and more readable if we process by comment body and respective functions?
> 
> E.g. (pseudo wise)
> 
> ```
> switch (commentBody) {
>     case "/assign":
>         executeAssign();
>         break;
>     case "/other":
>         executeOther();
>         break;
> }
> ```

It was mostly a port of dapr/dapr earlier. I have refactored it - but it comes with some boilerplates. This is more readable for sure but. Let me know if this works!

2022-03-29 06:08 UTC, XavierGeerinck approved these changes

2022-03-29 06:09 UTC, merged