Added TTL param to actor timer and reminder
dapr/js-sdk pull request #212
Opened 2022-03-14 19:40 UTC by amulyavarote

Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>

# Description

Added TTL param to actor timer and reminder.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #141 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-03-15 08:52 UTC, XavierGeerinck commented
Is there a file missing? I see a commit with a test file but I can't find it in the review?

2022-03-16 03:23 UTC, shubham1172 commented on daprdocs/content/en/js-sdk-docs/js-actors/_index.md
> +    ttl?: Temporal.Duration.from({ seconds: 1 }),
Optional parameter should be after required parameter.

2022-03-16 12:42 UTC, shubham1172 commented on daprdocs/content/en/js-sdk-docs/js-actors/_index.md
> +    ttl?: Temporal.Duration.from({ seconds: 1 }),
```suggestion
    ttl: Temporal.Duration.from({ seconds: 1 }),
```

2022-03-16 12:51 UTC, shubham1172 commented on src/actors/runtime/AbstractActor.ts
> +   * @param ttl time to live
```suggestion
   * @param ttl time duration after which the reminder will be expired and deleted
```

2022-03-16 12:55 UTC, shubham1172 commented on src/actors/runtime/ActorReminderData.ts
> +  constructor(reminderName: string, dueTime: number, ttl: number, period: number, state?: string | object) {
Same comments as above for `ttl`'s param documentation and optional nature.

2022-03-16 12:56 UTC, shubham1172 commented on test/actor/DemoActorReminder2Impl.ts
> +    await super.registerActorReminder("my-reminder-name", Temporal.Duration.from({ seconds: 2 }), Temporal.Duration.from({ seconds: 2 }), Temporal.Duration.from({ seconds: 1 }), 123);
nit: line break in params for readability

2022-03-16 12:56 UTC, shubham1172 commented on test/actor/DemoActorReminderImpl.ts
> +    await super.registerActorReminder("my-reminder-name", Temporal.Duration.from({ seconds: 2 }), Temporal.Duration.from({ seconds: 2 }), Temporal.Duration.from({ seconds: 1 }), 123);
nit: line break in params for readability

2022-03-16 12:56 UTC, shubham1172 requested changes
LGTM @amulyavarote, only had a few nits.

2022-04-19 18:18 UTC, merged