Rename dapr-client to @dapr/dapr
dapr/js-sdk pull request #256
Opened 2022-05-03 17:25 UTC by XavierGeerinck

Co-authored-by: @shubham1172 <shubhash@microsoft.com>
Signed-off-by: Xavier Geerinck <xavier.geerinck@gmail.com>

# Description

## Issue reference

Please reference the issue this PR will close: #223

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2022-05-04 03:44 UTC, shubham1172 commented on package.json
>      "version": "2.2.0-rc.0",
Note: We need to delete this from npm before running the workflow. Otherwise, it won't be able to overwrite the same version.

2022-05-04 03:58 UTC, shubham1172 commented on daprdocs/content/en/js-sdk-docs/_index.md
> +title: "JavaScript SDK for Actors"
Was this intentional? Should this be the index page?

2022-05-04 03:58 UTC, shubham1172 commented on .github/workflows/build.yml
> +    # - name: Configure to publish to @dapr/dapr
After pushing to @dapr/dapr, we should `sed` and push to dapr-client.

2022-05-04 03:59 UTC, shubham1172 commented on .github/workflows/build.yml
> +    #   uses: codecov/codecov-action@v1
Uncomment steps in this file.

2022-05-04 03:59 UTC, shubham1172 requested changes
LGTM, left a few comments!

2022-05-10 07:13 UTC, XavierGeerinck commented
LGTM, cannot test the build as NPM does not allow PRs to utilize secrets

2022-05-10 07:13 UTC, merged