Add documentation for logger usage and make keepAlive optional
dapr/js-sdk pull request #289
Opened 2022-06-07 12:27 UTC by shubham1172

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description

Add docs for logger.
Make `keepAlive` optional in `DaprClientOptions` - this ensures that the user can set logger options without being forced to set `keepAlive` explicitly.

## Issue reference

Please reference the issue this PR will close #288 and close #291 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [X] Extended the documentation

2022-06-09 09:00 UTC, XavierGeerinck submitted a review, later dismissed

2022-06-09 14:35 UTC, XavierGeerinck submitted a review, later dismissed

2022-06-13 05:39 UTC, shubham1172 commented
ping @XavierGeerinck

2022-06-13 11:26 UTC, XavierGeerinck requested changes

2022-06-13 11:29 UTC, XavierGeerinck approved these changes

2022-06-13 11:29 UTC, merged