Add warning message to dapr-client builds
dapr/js-sdk pull request #313
Opened 2022-07-05 18:34 UTC by shubham1172

# Description

This PR introduces a prebuild script to generate a src/version.ts file with package name and package version. The package name is then used in `DaprClient` to check if `dapr-client` is being used, and it shows a warning if true.

## Issue reference

Please reference the issue this PR will close: #260

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-07-12 11:57 UTC, XavierGeerinck requested changes
Should src/version.ts be committed as it is being auto generated?

2022-07-12 12:11 UTC, shubham1172 commented
> Should src/version.ts be committed as it is being auto generated?

Thought about the same but it's needed by our build systems that do not run a `npm run build`. One option is to explicitly run it. What do you think?

2022-07-13 11:31 UTC, shubham1172 commented
> Should src/version.ts be committed as it is being auto generated?

This has been checked-out of version control and workflows are updated. 

Only caveat, when users clone the repo for the first time, VS code will complain for the error until they run an `npm run build`.

2022-07-14 07:22 UTC, XavierGeerinck approved these changes

2022-07-14 07:22 UTC, merged