Api config
dapr/js-sdk pull request #345
Opened 2022-08-29 01:36 UTC by addjuarez

# Description

Update configuration api to use dictionaries.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #283

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

2022-08-29 22:11 UTC, amulyavarote commented on src/types/KeyConfig.type.ts
> +export type KeyConfigType = {
I think we can change this to `ConfigurationType`

2022-08-29 22:13 UTC, amulyavarote requested changes
Small comment to rename the type. The other changes look good to me.
And regarding the tests, can you please fix all the test cases and the github actions?

2022-08-30 11:30 UTC, shubham1172 commented
This proto is a part of unreleased Dapr, right? We should wait for the next release before changing this here. Thoughts?

/cc @XavierGeerinck

2022-08-30 11:32 UTC, shubham1172 requested changes

2022-08-30 11:32 UTC, shubham1172 commented on src/implementation/Client/GRPCClient/configuration.ts
> +        const configMap = Object()
```suggestion
        const configMap: { [k: string]: ConfigurationItem } = {};
```

2022-08-30 11:32 UTC, shubham1172 commented on src/implementation/Client/GRPCClient/configuration.ts
> +          metadata :  v.getMetadataMap().toObject().reduce((result: object, [key, value]) => {
The conversion from gRPC metadata to KeyValuePair, shall we move this to Client.utils.ts and reuse the same in both places?

2022-08-30 16:07 UTC, amulyavarote commented
> This proto is a part of unreleased Dapr, right? We should wait for the next release before changing this here. Thoughts?
> 
> /cc @XavierGeerinck

Yes. Makes sense. We have to wait until the dapr changes goes in like we always do.

2022-09-01 18:25 UTC, addjuarez commented on .github/workflows/test-e2e.yml
> +      DAPR_REF: '683a436ff1367e4ff2d27da2d79069c04ec2c46d'
The changes made to the configuration api are breaking and require a newer version of dapr.

2022-09-02 05:33 UTC, shubham1172 commented on .github/workflows/test-e2e.yml
> +      DAPR_REF: '683a436ff1367e4ff2d27da2d79069c04ec2c46d'
Yes, we should revert this and wait until Dapr's new version is released.

2022-09-06 02:45 UTC, artursouza commented
> > This proto is a part of unreleased Dapr, right? We should wait for the next release before changing this here. Thoughts?
> > /cc @XavierGeerinck
> 
> Yes. Makes sense. We have to wait until the dapr change goes in like we always do.

The Java SDK does not have this requirement as we allow to point to a git commit for dapr and build it as part of the SDK workflow for testing. Can this be achieved in this SDK too?

2022-09-06 04:59 UTC, shubham1172 commented
> > > This proto is a part of unreleased Dapr, right? We should wait for the next release before changing this here. Thoughts?
> > > /cc @XavierGeerinck
> > 
> > 
> > Yes. Makes sense. We have to wait until the dapr change goes in like we always do.
> 
> The Java SDK does not have this requirement as we allow to point to a git commit for dapr and build it as part of the SDK workflow for testing. Can this be achieved in this SDK too?

Yes, we can do that @artursouza, but I only have one concern. JavaScript SDK has a separate release cadence than runtime/Java-SDK, this will cause unreleased Dapr proto definitions to be a part of JavaScript SDK releases. For Java it must be ok since they only cut their release after Dapr release gets cut. WDYT?

+ @XavierGeerinck for thoughts

2022-09-06 06:20 UTC, XavierGeerinck commented
I think version management is always going to be difficult as we need to couple releases to certain Dapr versions, thus subsequent updates will not receive certain bug fixes or features.

We could adapt the testing workflow to point to a certain Dapr commit version, but I don't see the real benefit for it, what would this be? As we would be testing against the newest and be ready, but in the end the PRs are there and validated by the developers at the end stage to be released when the latest Dapr version is.

2022-10-17 10:16 UTC, shubham1172 commented
Hello @addjuarez, can you please fix conflicts?

2022-10-17 15:57 UTC, shubham1172 commented
@addjuarez the build is failing due to prettify, you can run `npm run pretty-fix` to solve these issues.

2022-10-17 16:49 UTC, shubham1172 submitted a review, later dismissed
LGTM, thanks @addjuarez! Please fix the e2e tests.

2022-10-26 06:50 UTC, shubham1172 commented on .github/workflows/test-e2e.yml
> -      DAPR_CLI_REF: '9472e6d977817243d6da28af3e3ca744414c54e6' # TODO, remove once DAPR CLI is upgraded to v1.7
@XavierGeerinck FYI, this reduced about 1.5 mins from our e2e pipeline 🥳

2022-11-02 06:15 UTC, shubham1172 commented on src/implementation/Client/GRPCClient/configuration.ts
> +      if (items.getLength() == 0) {
FYI, I added this in my recent commit. Apparently `stream.on` is returning two entries per change. The first one is empty, and second one contains actual data. Added this snippet to simply ignore the first empty callback.

2022-11-02 13:06 UTC, DeepanshuA commented
LGTM!

2022-11-02 18:14 UTC, amulyavarote commented
Looks good to me!

2022-11-02 18:15 UTC, amulyavarote approved these changes

2022-11-03 04:50 UTC, merged