Added an Option pass custom Headers in invocation
dapr/js-sdk pull request #386
Opened 2022-09-30 11:35 UTC by salmankhan-prs

Signed-off-by: pathan salman khan <pathans@geekyants.com>

# Description

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: [https://github.com/dapr/js-sdk/issues/218]

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [ ] Created/updated tests
- [ ] Extended the documentation

2022-09-30 11:41 UTC, salmankhan-prs commented
@shubham1172  I closed the previous PR  and created this Because of issues in reverting the changes

2022-09-30 12:25 UTC, salmankhan-prs commented
@shubham1172  can you verify the code now  I Got some free time If any changes  i will work on it

2022-09-30 13:34 UTC, shubham1172 commented on src/types/InvokerOptions.type.ts
> +* To pass Invoker options
```suggestion
* Options related to service invocation.
```

2022-09-30 13:35 UTC, shubham1172 commented on src/types/InvokerOptions.type.ts
> +  *Headers to include in service Invocation Request
```suggestion
  * Headers to include in service invocation request.   
```

2022-09-30 13:36 UTC, shubham1172 commented on src/implementation/Client/HTTPClient/invoker.ts
> +
Since we are allowing users to pass `headers`, we can skip setting `Content-Type` if it's already set. WDYT @XavierGeerinck?

2022-09-30 13:39 UTC, shubham1172 requested changes
@salmankhan-prs can you please fix the build and add tests? You can refer this for existing invoker e2e tests
https://github.com/dapr/js-sdk/blob/915260bf2399999fe82307b31e5c70c1dc42c3ef/test/e2e/main.http.test.ts#L114

2022-09-30 13:40 UTC, shubham1172 commented
Note, your build is failing due to `prettier`, you can run `npm run pretty` to see the issues, and `npm run pretty-fix` to fix the issues (this step will write the fixes to your files directly).

2022-09-30 13:43 UTC, salmankhan-prs commented
@shubham1172  npm run pretty  is not present package.json file

2022-09-30 13:45 UTC, shubham1172 commented
> @shubham1172 npm run pretty is not present package.json file

If you have merged with main and run `npm install`, you should be able to. See https://github.com/dapr/js-sdk/blob/2395a2103cb3e7474e628012189867bfe836ac78/package.json#L29

2022-10-04 04:28 UTC, shubham1172 commented
@salmankhan-prs can you please fix the build issues and conflicts?

2022-10-04 08:20 UTC, salmankhan-prs commented
> @salmankhan-prs can you please fix the build issues and conflicts?

@shubham1172  I resolved the prettier problem, so I'm not sure why the exact build is failing. Could you please assist me with that, as well as the fact that I made an empty commit without a sign for DCO and am unable to fix the commit with a sign

2022-10-04 08:25 UTC, shubham1172 commented
@salmankhan-prs looks like the last commit had a sign issue, you can try the following
```bash
git reset HEAD~1 # un-commit the last commit
git add .
git commit -sm "your message" # signed commit
git push -f <remote> <branch> # force push
```

Then, pull the latest `main` and merge it, resolving the conflict. Then finally run `npm run pretty-fix` to fix any lint issues.

2022-10-04 15:29 UTC, closed without merging