Deprecate req.body.data in favor of req.body
dapr/js-sdk pull request #426
Opened 2022-11-29 10:45 UTC by XavierGeerinck

Signed-off-by: Xavier Geerinck <xavier.geerinck@gmail.com>

# Description

We deprecated `req.body.data` in favor of `req.body` on the HTTP Pub Sub component. This means that data will now be in `req.body.data` and users should fetch accordingly.

The advantage of working this way is that providers that don't return data can be parsed and users can as well get the headers around it (e.g., source, pubsubname, datacontenttype, ...)

More practical, instead of returning:

```javascript
{
    hello: "world"
}
```

We will be returning:

```javascript
{
  data: { hello: 'world' },
  datacontenttype: 'application/json',
  id: '80e37aaa-a7e4-4484-a74e-2fd9e0194c47',
  pubsubname: 'pubsub-redis',
  source: 'test-suite',
  specversion: '1.0',
  time: '2022-11-29T11:30:16+01:00',
  topic: 'topic-1',
  traceid: '00-d0a8afe02330296da9046a7d827eecbe-8876a7ac21b31b6f-01',
  traceparent: '00-d0a8afe02330296da9046a7d827eecbe-8876a7ac21b31b6f-01',
  tracestate: '',
  type: 'com.dapr.event.sent'
}
```

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Extended the documentation

2022-12-09 03:47 UTC, shubham1172 requested changes
Some small changes!

2022-12-09 03:47 UTC, shubham1172 commented on src/implementation/Server/HTTPServer/HTTPServerImpl.ts
>          // @todo: This will be deprecated in an upcoming major version and only req.body will be returned
```suggestion
```

2022-12-09 03:47 UTC, shubham1172 commented on src/implementation/Server/HTTPServer/HTTPServerImpl.ts
>          // @todo: This will be deprecated in an upcoming major version and only req.body will be returned
We should also fix the comment above.

2022-12-09 03:47 UTC, shubham1172 commented on test/e2e/http/server.test.ts
> -      expect(mockBindingReceive.mock.calls.length).toBe(1);
Why are we removing these?

2022-12-09 03:47 UTC, shubham1172 commented on test/e2e/http/server.test.ts
> +    it("should receive the entire body instead of just data, this also contains the content type, time, traces, ...", async () => {
```suggestion
    it("should be able to receive the entire cloud event", async () => {
```

2023-01-08 04:05 UTC, shubham1172 commented
/ping @XavierGeerinck

2023-01-09 08:29 UTC, XavierGeerinck commented on test/e2e/http/server.test.ts
> -      expect(mockBindingReceive.mock.calls.length).toBe(1);
Re-added

2023-01-17 16:27 UTC, XavierGeerinck commented
Closing in favor of #443

2023-01-17 16:27 UTC, closed without merging